services:
  postgres:
    image: postgres:16-alpine
    container_name: watts-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: watts
      POSTGRES_PASSWORD: password
      POSTGRES_DB: watts
    ports:
      - '5439:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U watts']
      interval: 10s
      timeout: 5s
      retries: 5

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: watts-dragonfly
    restart: unless-stopped
    ulimits:
      memlock: -1
    command:
      [
        '--default_lua_flags=allow-undeclared-keys',
        '--requirepass=dragonfly',
        '--admin_port=6380',
        '--admin_nopass',
        '--slowlog_log_slower_than=10000',
        '--slowlog_max_len=128'
      ]
    ports:
      - '6379:6379'
      - '6380:6380'
    volumes:
      - dragonfly_data:/data
    healthcheck:
      test: ['CMD-SHELL', 'REDISCLI_AUTH=dragonfly redis-cli ping | grep -q PONG']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  dragonfly_data:
